- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{ item }}
    with_items:
      - build-essential
      - nodejs
      - npm
      - tmux
      - zsh
      - ansible
      - ansible-lint
  - name: Create project dirs
    file:
      path: "/home/*/{{ item }}"
      state: directory
    with_items:
      - personal
      - work
      - external
  - name: Debug
    debug:
      msg: "{{ lookup('env', 'HOME') }}"
